### ISSUE TITLE
Query on slave returning wrong results in test

### ISSUE THREAD

**Issue by agis-** [kenn/slavery#15]
Hey,

After switching some queries to be sent to the slaves, I've noticed a specific test failing due to the `on_slave` scope returning wrong results:

```
[2] pry(#<RSpec::ExampleGroups::ShopsController::GETIndex>)> Shop.where("created_on > ?", 5.days.ago)
[master]  Shop Load (1.2ms)  SELECT `shops`.* FROM `shops` WHERE (created_on > '2017-01-14 11:54:33.639784')
 # => [#<Shop:0x007fa103931290>]
# returns the `Shop` record as expected, test succeeds

[3] pry(#<RSpec::ExampleGroups::ShopsController::GETIndex>)> Shop.on_slave.where("created_on > ?", 5.days.ago)
[slave]  Shop Load (0.8ms)  SELECT `shops`.* FROM `shops` WHERE (created_on > '2017-01-14 11:56:41.160893')
# => [] 
# test fails
```

Oddly enough, `Slavery.on_slave` still sends the queries to the master:

```
[4] pry(#<RSpec::ExampleGroups::ShopsController::GETIndex>)> Slavery.on_slave { Shop.where("created_on > ?", 5.days.ago) }
[master]  Shop Load (0.9ms)  SELECT `shops`.* FROM `shops` WHERE (created_on > '2017-01-14 11:58:43.070048')
# => [#<Shop:0x007fa103931290>]
```

The failing test is roughly the following:

```ruby
  describe "foo" do
    let!(:shop) { FactoryGirl.create(:shop) }
    
    it "foooooo" do
      shop.update_attribute :created_on, 3.days.ago
      shop.update_attribute :updated_on, 3.days.ago

      get :index, { :since => 5.days.ago }
      expect(assigns(:shops)).to eq([shop])
    end
  end
```

I've also tried reducing the query to `Shop.count`/`Shop.on_slave.count`, same issue: the result is `1` vs. `0`.

Any ideas?

Thanks

**Comment by agis-** [comment]
A simpler demonstration, inside the same test:

```
[7] pry(#<RSpec::ExampleGroups::EarthShopsController::GETIndex>)> Shop.count
[master]   (0.6ms)  SELECT COUNT(*) FROM `shops`
=> 1
[8] pry(#<RSpec::ExampleGroups::EarthShopsController::GETIndex>)> Slavery.on_slave { Shop.count }
[slave]   (0.6ms)  SELECT COUNT(*) FROM `shops`
=> 0
[9] pry(#<RSpec::ExampleGroups::EarthShopsController::GETIndex>)> Shop.on_slave.count
[slave]   (0.6ms)  SELECT COUNT(*) FROM `shops`
=> 0
```

**Comment by agis-** [comment]
It seems that Slavery doesn't execute the query on `master` if it's inside a transactional test, therefore cannot see the changes performed inside the transaction which started on `master`.

Is this intented? Shouldn't we detect that we're inside a test's transaction (ie transactional fixtures is on) and run all queries on master?

**Comment by agis-** [comment]
@kenn Any thoughts on this?

**Comment by kenn** [comment]
Slavery cannot be used inside a transaction - if you try, you'll see an exception. Only exception allowed is transactional fixtures for tests.

Do you actually use separate database for `test` and `test_slave`? Otherwise it's weird to see different results anyway. If you point to the same database with read-only access you should see the same result no matter what.

And if you use separate databases, there will be delay synching from master to slave, which makes the test indeterministic depending on the timing.

Either way, I think it's an issue specific to your test, not of Slavery.

**Comment by agis-** [comment]
I use a single database in test so `test` and `test_slave` are identical. The access isn't read-only but I don't think this is the cause of this failure.

I think this issue is expected: if a transaction is started (and isn't commited) in connection `A`, then a connection `B` won't see the changes of the connection `A`.

I've created a sample app demonstrating the issue: https://github.com/agis-/slavery-gh-15 (commits are separated logically so you can just take a look at https://github.com/agis-/slavery-gh-15/commit/d0ba9f145f03122ca689440ba423ee2fbb04c92a).

In other words, when transactional fixtures are enabled, this sounds expected to me:

```ruby
+  test "foo" do
+    User.create!
+
+    assert_equal 1, User.count
+    assert_equal 1, User.on_slave.count # fails
+  end

test "foo" do
   # this starts in a transaction `master` connection (let's call it `A`), but is *not* commited
  User.create!

 # this succeeds since it's run on the same `A` connection
  assert_equal 1, User.count

 # this fails since it runs on another connection (let's call it `B`), which has no knowledge of the
 #`A`'s changes, since that transaction is not commited yet
  assert_equal 1, User.on_slave.count

  # A's transaction is rolled back
end
```

**Comment by kenn** [comment]
Are you using sqlite3 for the test? It's [not suppored for nested transactions](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html). Can you try either MySQL or PostgreSQL?

Also I'm not sure why you think `User.create!` is not committed.

In any case, I already mentioned that Slavery does not support transaction, so you can either force commit it or just use fixture.

**Comment by agis-** [comment]
The issue persists with MySQL ([commit](https://github.com/agis-/slavery-gh-15/commit/2283abae500e2686ae5be226f894eda252c2a933)).

`User.create!` indeed does *not* create the record because this is how transactional fixtures work. The transaction is not commited but is rolled-back at the end of the test. `log/test.log` demonstrates this behavior, which is expected when using transactional fixtures:

```
[master]   (0.1ms)  SET FOREIGN_KEY_CHECKS = 1
[master]   (0.1ms)  BEGIN
------------------
UserTest: test_foo
------------------
[master]   (0.2ms)  SELECT COUNT(*) FROM `users`
[slave]   (0.3ms)  SELECT COUNT(*) FROM `users`
[master]   (0.1ms)  SAVEPOINT active_record_1
[master]  SQL (0.2ms)  INSERT INTO `users` (`created_at`, `updated_at`) VALUES ('2017-01-24 10:34:25', '2017-01-24 10:34:25')
[master]   (0.1ms)  RELEASE SAVEPOINT active_record_1
[master]   (0.2ms)  SELECT COUNT(*) FROM `users`
[slave]   (0.2ms)  SELECT COUNT(*) FROM `users`
[master]   (0.6ms)  ROLLBACK
```

**Comment by agis-** [comment]
I was thinking something like this, which is minimally intrusive I think:

```diff
diff --git a/lib/slavery/base.rb b/lib/slavery/base.rb
index f061bb5..eaa702f 100644
--- a/lib/slavery/base.rb
+++ b/lib/slavery/base.rb
@@ -13,7 +13,7 @@ module Slavery
     def decide_with(target)
       raise Slavery::Error.new('on_slave cannot be used inside transaction block!') if inside_transaction?

-      if Slavery.disabled
+      if Slavery.disabled || inside_transactional_fixture?
         :master
       else
         target
@@ -25,6 +25,13 @@ module Slavery
       open_transactions > Slavery::Transaction.base_depth
     end

+    def inside_transactional_fixture?
+      testcase = ActiveSupport::TestCase
+      defined?(testcase) &&
+        testcase.respond_to?(:use_transactional_fixtures) &&
+        testcase.try(:use_transactional_fixtures)
+    end
+
```

Thoughts?

**Comment by kenn** [comment]
The rationale for global disable in tests is that, we don't usually care if a read is from master or slave. It should just work.

But in a specific test case where you want to test the behavior of Slavery, you can turn it back on (Slavery.disabled = false) - but the same issue is still there if you write to the database before that. We can write in README that we should not write to the database though.

**Comment by kenn** [comment]
Hmm, the change makes it impossible to test the behavior because `inside_transactional_fixture?` is baked in. I would change the default value of Slavery.disabled instead, so you can easily change where you need to do so.

**Comment by agis-** [comment]
Hm yeah, changing the default seems like the way to go. At this point I'm thinking if a README section instructing users to just disable slavery manually in test is a better solution.

Anyway, I'm submitting a PR.

**Comment by kenn** [comment]
On second thought, I'm hesitant to disable entirely in all tests.

- It just gives a false illusion that Slavery doesn't break anything.
- If it's just `Slavery.disable = true`, you can do it in `test_helper`.
- I think missing uncommitted data can be a good test to find that slave read can lag behind master. You shouldn't use `on_slave` where immediate consistency is required.

So instead, I would suggest something like this in `test_helper`:

```ruby
if ActiveRecord::Base.connection.supports_transaction_isolation?
  ActiveRecord::Base.connection.execute('SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED')
  ...
end
```

or

```ruby
User.transaction(isolation: :read_uncommitted) do
  ...
end
```

in a specific test where you actually want phantom read. It's probably a documentation issue more or less.

What do you think?

**Comment by agis-** [comment]
Totally agreed.

Personally I'd go with a `Slavery.disabled = true` as I think it's just fine. I can't think of a use-case where you'd like to use slave reads in a test environment.

Do you think we should mention the transaction isolation stuff in the README? I think it might be too much for the common case (where ppl are using a single database for testing).

I think something like this is enough:

> Slavery does not work with Rails' transactional fixtures, since the slave connection is not aware of the changes performed in the master connection. You are suggested to disable Slavery in the test environment by putting the following in `test/test_helper.rb` or `spec/spec_helper.rb`:
> ```
> Slavery.disabled = true
> ```

**Comment by kenn** [comment]
It works just fine with transactional fixtures (I do it all the time), but fails **when and only when** you write to the database inside the same test. So:

> When `use_transactional_fixtures` is set to `true`, it's NOT recommended to write to the database besides fixtures, since the slave connection is not aware of the changes being performed in the master connection due to [transaction isolation](https://en.wikipedia.org/wiki/Isolation_(database_systems)). In that case, you are suggested to disable...

is better?

**Comment by agis-** [comment]
@kenn Updated: https://github.com/kenn/slavery/pull/16
