### ISSUE TITLE
Is there a way to connect to multiple slaves?

### ISSUE THREAD

**Issue by larryzhao** [kenn/slavery#19]
I couldn't find it in the guide, is it possible to do with Slavery?

**Comment by kenn** [comment]
At this moment, Slavery does not support multiple slaves. It's certainly doable with an API like:

```ruby
User.on_slave(:replica2).all
```

Pull requests are welcome! 😎

Also keep in mind that [3-level DB config](https://github.com/rails/rails/pull/28095) is coming.

**Comment by kenn** [comment]
It's supported in v3.0
