### ISSUE TITLE
How disable Slavery for single model?

### ISSUE THREAD

**Issue by PNixx** [kenn/slavery#24]
I have disable reading from slave for single model, for example `Action`.

```
class Action < ActiveRecord::Base
  self.slavery_dasabled = true
end

Slavery.on_slave do
  users = User.count
  User.each do |user|
    actions = user.actions.count
  end
end
```

**Comment by kenn** [comment]
Can't do per-model, but you can do per-query using `Slavery.on_master`.

```ruby
Slavery.on_slave do
  users = User.count
  User.each do |user|
    actions = Slavery.on_master do
      user.actions.count
    end
  end
end
```

Please reopen if it doesn't work for you.

**Comment by ronakjangir47** [comment]
@kenn If we are using `establish_connection` in any of our model to connect this model with different database. 

For example 
````ruby
class Notification < ApplicationRecord
  establish_connection "notifications_#{Rails.env}".to_sym
end
````

But if we wan't to access `Notification` records within the `stand_by` block like below then it run the query on stand_by database instead `notifications` database but we want to use `notifications` database of this model.
````ruby
Standby.on_standby do
  Notification.count
end
````

Your suggested solution can work in our case but there are multiple instances in our application where we will need to make this change. Doesn't sound like a good approach. Can you please suggest other solution? I can work on more digging if you are willing to add support of this feature also please provide me the right direction.

**Comment by kenn** [comment]
If you are manually handling `establish_connection` yourself, Standby is not the right solution for your case, because connection holder can only one standby connection.
